#!/bin/bash

##hook this shit to the desktop environment autostart

##custom Xrandr settings
xrandr --setprovideroutputsource 1 0
xrandr --newmode "1280x1024_60.00"  109.00  1280 1368 1496 1712  1024 1027 1034 1063 -hsync +vsync
xrandr --addmode VGA-1-0 "1280x1024_60.00"
xrandr --auto --output VGA-1-0  --mode 1280x1024_60.00 --left-of HDMI-0

setxkbmap latam
